language: node_js
node_js: 
  - "8"
cache:
  yarn: true
script:
  - npm run unit
before_script:
  - npm install -g coveralls
after_script:
  - "cat ./test/unit/coverage/lcov.info | coveralls"
env:
  global:
    secure: "Oqcv5xdhOW03bVl1K7xiVy5xncZ9hSLExH+S9AWnTbZHCncTZxwbXgm+1ioRig2Lisz63QtA+t2foB+zmka6yTujd7Y31ZP4kVJdInQGRhnF/zdhWPcf/9k/PLtKkhnatiQxHuJYgFWo70wc6lQtFQUNfmhpmj+gcSBfrKAjh0oJOP3NHSAbhE1g/w5hr7rxax+yDACMhkJLE6Vzj3TxAY6JU1noxVvN8HUHUY0JbGk1zsOTIxKQIUXKeQTpQDnSaAq0tf/rvhmI191yuCIILl7uwF8fMQJ+cM0Amm4Casv0EMHrnOhIzG9+YUeNWFO2zZbht491c+W14BeMGTpTYh+7g32HbUn67Z7JwIRq2XrCt7qR3TtJTpo1SnbxIMmLigmK8JUbKEb61ro4am95MnDgBocDbWNJ8AvfCW77Ojex42HmOG5m7dhc7ua7a76hkAGBOUHlT0iG6FWOY3zG1rXt0mcG8L60mNT239c7kL/axaPr3yHx12kDKrElQ37cqdl54h3OBWL+a1RFKfE9vpq7U9Rqjwe5DU249cq1tPrXgQ2HvgZd6A98GkdxqKTdMkX+CvjaZzRfVk2i9Gkyu7bWrAEJYIn6GspwsYreg3E+C4/foIoF6P2MztWzPjYupj0j28/lzRifmxIf/EciLDJ2+KrCrzFkFblbeS+LLSw="
branches:
  only:
    - master