language: node_js
node_js: 
  - "8"
cache:
  yarn: true
script:
  - npm run unit
before_script:
  - npm install -save coveralls
after_script:
  - "jest --coverage && cat ./coverage/lcov.info | coveralls"